trigger-actions-framework/main/default/objects/sObject_Trigger_Setting__mdt/sObject_Trigger_Setting__mdt.object-meta.xml
<CustomObject>
    <label>sObject Trigger Setting</label>
    <pluralLabel>sObject Trigger Settings</pluralLabel>
</CustomObject>

trigger-actions-framework/main/default/objects/sObject_Trigger_Setting__mdt/fields/Bypass_Execution__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Execution__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set this to true to bypass all Trigger Actions from being called on this sObject</description>
    <inlineHelpText>Set this to true to bypass all Trigger Actions from being called on this sObject</inlineHelpText>
    <label>Bypass Execution</label>
    <type>Checkbox</type>
</CustomField>

trigger-actions-framework/main/default/objects/sObject_Trigger_Setting__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sObject you would like to define trigger actions for.</description>
    <inlineHelpText>Select the sObject you would like to define trigger actions for.</inlineHelpText>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>sObject_Trigger_Settings</relationshipLabel>
    <relationshipName>sObject_Trigger_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

application/base/main/default/objects/Trigger_Action__mdt/Trigger_Action__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Action</label>
    <pluralLabel>Trigger Actions</pluralLabel>
</CustomObject>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/After_Delete__c.field-meta.xml
<CustomField>
    <fullName>After_Delete__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the after delete context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the after delete context</inlineHelpText>
    <label>After Delete</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>After Delete</relationshipLabel>
    <relationshipName>After_Delete_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

application/base/main/default/objects/Trigger_Action__mdt/fields/After_Insert__c.field-meta.xml
<CustomField>
    <fullName>After_Insert__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the after insert context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the after insert context</inlineHelpText>
    <label>After Insert</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>After Insert</relationshipLabel>
    <relationshipName>After_Insert_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/After_Undelete__c.field-meta.xml
<CustomField>
    <fullName>After_Undelete__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the after undelete context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the after undelete context</inlineHelpText>
    <label>After Undelete</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>After Undelete</relationshipLabel>
    <relationshipName>After_Undelete_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

application/base/main/default/objects/Trigger_Action__mdt/fields/After_Update__c.field-meta.xml
<CustomField>
    <fullName>After_Update__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the after update context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the after update context</inlineHelpText>
    <label>After Update</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>After Update</relationshipLabel>
    <relationshipName>After_Update_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>Enter the name of the Apex Class which defines the action to be taken</description>
    <inlineHelpText>Enter the name of the Apex Class which defines the action to be taken</inlineHelpText>
    <label>Apex Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Before_Delete__c.field-meta.xml
<CustomField>
    <fullName>Before_Delete__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the before delete context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the before delete context</inlineHelpText>
    <label>Before Delete</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>Before Delete</relationshipLabel>
    <relationshipName>Before_Delete_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Before_Insert__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the before insert context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the before insert context</inlineHelpText>
    <label>Before Insert</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>Before Insert</relationshipLabel>
    <relationshipName>Before_Insert_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Before_Update__c.field-meta.xml
<CustomField>
    <fullName>Before_Update__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the before update context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the before update context</inlineHelpText>
    <label>Before Update</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>Before Update</relationshipLabel>
    <relationshipName>Before_Update_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

application/base/main/default/objects/Trigger_Action__mdt/fields/Bypass_Execution__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Execution__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set this to true to bypass this Trigger Action from being called</description>
    <inlineHelpText>Set this to true to bypass this Trigger Action from being called</inlineHelpText>
    <label>Bypass Execution</label>
    <type>Checkbox</type>
</CustomField>

application/base/main/default/objects/Trigger_Action__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

application/base/main/default/classes/MetadataTriggerHandlerTest.cls
/*
   Copyright 2020 Google LLC

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */


@IsTest
private class MetadataTriggerHandlerTest {
	
	@IsTest
	private static void sobject_triggerNew () {
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerNew = new List<Account> {new Account()};
		String response;
		Exception myException;
		test.startTest();
		try {
			response = handler.sObjectName;
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
		System.assertEquals('Account', response);
	}
	
	@IsTest
	private static void sobject_triggerOld () {
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerOld = new List<Account> {new Account()};
		String response;
		Exception myException;
		test.startTest();
		try {
			response = handler.sObjectName;
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
		System.assertEquals('Account', response);
	}
	
	@IsTest
	private static void triggerActionsForThisObject () {
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerNew = new List<Account> {new Account()};
		List<Trigger_Action__mdt> response;
		Exception myException;
		test.startTest();
		try {
			response = handler.triggerActionsForThisObject;
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
		System.assertNotEquals(null, response);
	}
	
	@IsTest
	private static void set_triggerActionsForThisObject () {
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerNew = new List<Account> {new Account()};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt beforeInsert = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeInsert',
			Before_Insert__r = setting,
			Before_Insert__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		Trigger_Action__mdt afterInsert = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.AfterInsert',
			After_Insert__r = setting,
			After_Insert__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		Trigger_Action__mdt beforeUpdate = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeUpdate',
			Before_Update__r = setting,
			Before_Update__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		Trigger_Action__mdt afterUpdate = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.AfterUpdate',
			After_Update__r = setting,
			After_Update__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		Trigger_Action__mdt beforeDelete = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeDelete',
			Before_Delete__r = setting,
			Before_Delete__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		Trigger_Action__mdt afterDelete = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.AfterDelete',
			After_Delete__r = setting,
			After_Delete__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		Trigger_Action__mdt afterUndelete = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.AfterUndelete',
			After_Undelete__r = setting,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			beforeInsert, afterInsert, beforeUpdate, afterUpdate, beforeDelete, afterDelete, afterUndelete
		};
		Exception myException;
		test.startTest();
		try {
			response = handler.triggerActionsForThisObject;
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
		System.assertNotEquals(null, response);
		System.assertEquals(7, response.size());
	}
	
	@IsTest
	private static void beforeInsert_success () {
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerNew = new List<Account> {new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType))};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeInsert',
			Before_Insert__r = setting,
			Before_Insert__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.beforeInsert(handler.triggerNew);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
	}
	
	@IsTest
	private static void beforeInsert_fail () {
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.sObjectName = 'Account';
		handler.triggerNew = new List<Account> {new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType))};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.AfterInsert',
			Before_Insert__r = setting,
			Before_Insert__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.beforeInsert(handler.triggerNew);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
		System.assertEquals(true, ApexPages.hasMessages());
		System.assertEquals(1, ApexPages.getMessages().size());
		System.assertEquals(true, ApexPages.getMessages()[0].getDetail().contains(String.format(MetadataTriggerHandler.INVALID_TYPE_ERROR, new String[] {'MetadataTriggerHandlerTest.AfterInsert', String.valueOf(System.TriggerOperation.BEFORE_INSERT)})));
	}
	
	@IsTest
	private static void afterInsert_success () {
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerNew = new List<Account> {new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType))};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.AfterInsert',
			After_Insert__r = setting,
			After_Insert__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.afterInsert(handler.triggerNew);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
	}
	
	@IsTest
	private static void afterInsert_fail () {
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.sObjectName = 'Account';
		handler.triggerNew = new List<Account> {new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType))};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeInsert',
			After_Insert__r = setting,
			After_Insert__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.afterInsert(handler.triggerNew);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
		System.assertEquals(true, ApexPages.hasMessages());
		System.assertEquals(1, ApexPages.getMessages().size());
		System.assertEquals(true, ApexPages.getMessages()[0].getDetail().contains(String.format(MetadataTriggerHandler.INVALID_TYPE_ERROR, new String[] {'MetadataTriggerHandlerTest.BeforeInsert', String.valueOf(System.TriggerOperation.AFTER_INSERT)})));
	}
	
	@IsTest
	private static void beforeUpdate_success () {
		Account myAccount = new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType));
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerNew = new List<Account> {myAccount};
		handler.triggerOld = new List<Account> {myAccount};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeUpdate',
			Before_Update__r = setting,
			Before_Update__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.beforeUpdate(handler.triggerNew, handler.triggerOld);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
	}
	
	@IsTest
	private static void beforeUpdate_fail () {
		Account myAccount = new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType));
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerNew = new List<Account> {myAccount};
		handler.triggerOld = new List<Account> {myAccount};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeInsert',
			Before_Update__r = setting,
			Before_Update__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.beforeUpdate(handler.triggerNew, handler.triggerOld);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
		System.assertEquals(true, ApexPages.hasMessages());
		System.assertEquals(1, ApexPages.getMessages().size());
		System.assertEquals(true, ApexPages.getMessages()[0].getDetail().contains(String.format(MetadataTriggerHandler.INVALID_TYPE_ERROR, new String[] {'MetadataTriggerHandlerTest.BeforeInsert', String.valueOf(System.TriggerOperation.BEFORE_UPDATE)})));
	}
	
	@IsTest
	private static void afterUpdate_success () {
		Account myAccount = new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType));
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerNew = new List<Account> {myAccount};
		handler.triggerOld = new List<Account> {myAccount};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.AfterUpdate',
			After_Update__r = setting,
			After_Update__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.afterUpdate(handler.triggerNew, handler.triggerOld);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
	}
	
	@IsTest
	private static void afterUpdate_fail () {
		Account myAccount = new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType));
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerNew = new List<Account> {myAccount};
		handler.triggerOld = new List<Account> {myAccount};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeInsert',
			After_Update__r = setting,
			After_Update__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.afterUpdate(handler.triggerNew, handler.triggerOld);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
		System.assertEquals(true, ApexPages.hasMessages());
		System.assertEquals(1, ApexPages.getMessages().size());
		System.assertEquals(true, ApexPages.getMessages()[0].getDetail().contains(String.format(MetadataTriggerHandler.INVALID_TYPE_ERROR, new String[] {'MetadataTriggerHandlerTest.BeforeInsert', String.valueOf(System.TriggerOperation.AFTER_UPDATE)})));
	}
	
	@IsTest
	private static void beforeDelete_success () {
		Account myAccount = new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType));
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerOld = new List<Account> {myAccount};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeDelete',
			Before_Delete__r = setting,
			Before_Delete__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.beforeDelete(handler.triggerOld);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
	}
	
	@IsTest
	private static void beforeDelete_fail () {
		Account myAccount = new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType));
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerOld = new List<Account> {myAccount};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeInsert',
			Before_Delete__r = setting,
			Before_Delete__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.beforeDelete(handler.triggerOld);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
		System.assertEquals(true, ApexPages.hasMessages());
		System.assertEquals(1, ApexPages.getMessages().size());
		System.assertEquals(true, ApexPages.getMessages()[0].getDetail().contains(String.format(MetadataTriggerHandler.INVALID_TYPE_ERROR, new String[] {'MetadataTriggerHandlerTest.BeforeInsert', String.valueOf(System.TriggerOperation.BEFORE_DELETE)})));
	}
	
	@IsTest
	private static void afterDelete_success () {
		Account myAccount = new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType));
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerOld = new List<Account> {myAccount};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.AfterDelete',
			After_Delete__r = setting,
			After_Delete__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.afterDelete(handler.triggerOld);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
	}
	
	@IsTest
	private static void afterDelete_fail () {
		Account myAccount = new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType));
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerOld = new List<Account> {myAccount};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeInsert',
			After_Delete__r = setting,
			After_Delete__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.afterDelete(handler.triggerOld);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
		System.assertEquals(true, ApexPages.hasMessages());
		System.assertEquals(1, ApexPages.getMessages().size());
		System.assertEquals(true, ApexPages.getMessages()[0].getDetail().contains(String.format(MetadataTriggerHandler.INVALID_TYPE_ERROR, new String[] {'MetadataTriggerHandlerTest.BeforeInsert', String.valueOf(System.TriggerOperation.AFTER_DELETE)})));
	}
	
	@IsTest
	private static void afterUndelete_success () {
		Account myAccount = new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType));
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerOld = new List<Account> {myAccount};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.AfterUndelete',
			After_Undelete__r = setting,
			After_Undelete__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.afterUndelete(handler.triggerOld);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
	}
	
	@IsTest
	private static void afterUndelete_fail () {
		Account myAccount = new Account(Name = 'My Account', Id = TestUtility.getFakeId(Account.SObjectType));
		MetadataTriggerHandler handler = new MetadataTriggerHandler();
		handler.triggerOld = new List<Account> {myAccount};
		List<Trigger_Action__mdt> response;
		sObject_Trigger_Setting__mdt setting = new sObject_Trigger_Setting__mdt(
			SObject__c = 'Account',
			Id = TestUtility.getFakeId(sObject_Trigger_Setting__mdt.SObjectType)
		);
		Trigger_Action__mdt action = new Trigger_Action__mdt(
			Apex_Class_Name__c = 'MetadataTriggerHandlerTest.BeforeInsert',
			After_Undelete__r = setting,
			After_Undelete__c = setting.Id,
			Order__c = 1,
			Bypass_Execution__c = false
		);
		handler.triggerActionsForThisObject = new List<Trigger_Action__mdt> {
			action
		};
		Exception myException;
		test.startTest();
		try {
			handler.afterUndelete(handler.triggerOld);
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		System.assertEquals(null, myException);
		System.assertEquals(true, ApexPages.hasMessages());
		System.assertEquals(1, ApexPages.getMessages().size());
		System.assertEquals(true, ApexPages.getMessages()[0].getDetail().contains(String.format(MetadataTriggerHandler.INVALID_TYPE_ERROR, new String[] {'MetadataTriggerHandlerTest.BeforeInsert', String.valueOf(System.TriggerOperation.AFTER_UNDELETE)})));
	}

	
	@IsTest
	private static void bypass_success () {
		Exception myException;
		test.startTest();
		try {
			MetadataTriggerHandler.bypass('MetadataTriggerHandlerTest.BeforeInsert');
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		system.assertEquals(null, myException);
		System.assert (MetadataTriggerHandler.bypassedActions.contains('MetadataTriggerHandlerTest.BeforeInsert'));
	}
	
	@IsTest
	private static void clearBypass_success () {
		Exception myException;
		test.startTest();
		try {
			MetadataTriggerHandler.bypass('MetadataTriggerHandlerTest.BeforeInsert');
			MetadataTriggerHandler.clearBypass('MetadataTriggerHandlerTest.BeforeInsert');
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		system.assertEquals(null, myException);
		System.assert (!MetadataTriggerHandler.bypassedActions.contains('MetadataTriggerHandlerTest.BeforeInsert'));
	}
	
	@IsTest
	private static void isBypassed_success () {
		Boolean isBypassed;
		MetadataTriggerHandler.bypass('MetadataTriggerHandlerTest.BeforeInsert');
		Exception myException;
		test.startTest();
		try {
			isBypassed = MetadataTriggerHandler.isBypassed('MetadataTriggerHandlerTest.BeforeInsert');
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		system.assertEquals(null, myException);
		System.assertEquals(true, isBypassed);
	}
	
	@IsTest
	private static void clearAllBypasses_success () {
		MetadataTriggerHandler.bypass('MetadataTriggerHandlerTest.BeforeInsert');
		Exception myException;
		test.startTest();
		try {
			MetadataTriggerHandler.clearAllBypasses();
		} catch (Exception e) {
			myException = e;
		}
		test.stopTest();
		system.assertEquals(null, myException);
		System.assertEquals(0, MetadataTriggerHandler.bypassedActions.size());
	}
	
	public class BeforeInsert implements TriggerAction.BeforeInsert {
		public void beforeInsert(List<SObject> newList) {
		}
	}
	public class AfterInsert implements TriggerAction.AfterInsert {
		public void afterInsert(List<SObject> newList) {
		}
	}
	public class BeforeUpdate implements TriggerAction.BeforeUpdate {
		public void beforeUpdate(List<SObject> newList, List<SObject> oldList) {
		}
	}
	public class AfterUpdate implements TriggerAction.AfterUpdate {
		public void afterUpdate(List<SObject> newList, List<SObject> oldList) {
		}
	}
	public class BeforeDelete implements TriggerAction.BeforeDelete {
		public void beforeDelete(List<SObject> oldList) {
		}
	}
	public class AfterDelete implements TriggerAction.AfterDelete {
		public void afterDelete(List<SObject> newList) {
		}
	}
	public class AfterUndelete implements TriggerAction.AfterUndelete {
		public void afterUndelete(List<SObject> newList) {
		}
	}
	
}