trigger-actions-framework/main/default/objects/sObject_Trigger_Setting__mdt/sObject_Trigger_Setting__mdt.object-meta.xml
<CustomObject>
    <label>sObject Trigger Setting</label>
    <pluralLabel>sObject Trigger Settings</pluralLabel>
</CustomObject>

trigger-actions-framework/main/default/objects/sObject_Trigger_Setting__mdt/fields/Bypass_Execution__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Execution__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set this to true to bypass all Trigger Actions from being called on this sObject</description>
    <inlineHelpText>Set this to true to bypass all Trigger Actions from being called on this sObject</inlineHelpText>
    <label>Bypass Execution</label>
    <type>Checkbox</type>
</CustomField>

trigger-actions-framework/main/default/objects/sObject_Trigger_Setting__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sObject you would like to define trigger actions for.</description>
    <inlineHelpText>Select the sObject you would like to define trigger actions for.</inlineHelpText>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>sObject_Trigger_Settings</relationshipLabel>
    <relationshipName>sObject_Trigger_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

application/base/main/default/objects/Trigger_Action__mdt/Trigger_Action__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Action</label>
    <pluralLabel>Trigger Actions</pluralLabel>
</CustomObject>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/After_Delete__c.field-meta.xml
<CustomField>
    <fullName>After_Delete__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the after delete context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the after delete context</inlineHelpText>
    <label>After Delete</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>After Delete</relationshipLabel>
    <relationshipName>After_Delete_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

application/base/main/default/objects/Trigger_Action__mdt/fields/After_Insert__c.field-meta.xml
<CustomField>
    <fullName>After_Insert__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the after insert context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the after insert context</inlineHelpText>
    <label>After Insert</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>After Insert</relationshipLabel>
    <relationshipName>After_Insert_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/After_Undelete__c.field-meta.xml
<CustomField>
    <fullName>After_Undelete__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the after undelete context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the after undelete context</inlineHelpText>
    <label>After Undelete</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>After Undelete</relationshipLabel>
    <relationshipName>After_Undelete_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

application/base/main/default/objects/Trigger_Action__mdt/fields/After_Update__c.field-meta.xml
<CustomField>
    <fullName>After_Update__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the after update context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the after update context</inlineHelpText>
    <label>After Update</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>After Update</relationshipLabel>
    <relationshipName>After_Update_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>Enter the name of the Apex Class which defines the action to be taken</description>
    <inlineHelpText>Enter the name of the Apex Class which defines the action to be taken</inlineHelpText>
    <label>Apex Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Before_Delete__c.field-meta.xml
<CustomField>
    <fullName>Before_Delete__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the before delete context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the before delete context</inlineHelpText>
    <label>Before Delete</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>Before Delete</relationshipLabel>
    <relationshipName>Before_Delete_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Before_Insert__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the before insert context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the before insert context</inlineHelpText>
    <label>Before Insert</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>Before Insert</relationshipLabel>
    <relationshipName>Before_Insert_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Before_Update__c.field-meta.xml
<CustomField>
    <fullName>Before_Update__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the before update context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the before update context</inlineHelpText>
    <label>Before Update</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>Before Update</relationshipLabel>
    <relationshipName>Before_Update_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

application/base/main/default/objects/Trigger_Action__mdt/fields/Bypass_Execution__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Execution__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set this to true to bypass this Trigger Action from being called</description>
    <inlineHelpText>Set this to true to bypass this Trigger Action from being called</inlineHelpText>
    <label>Bypass Execution</label>
    <type>Checkbox</type>
</CustomField>

application/base/main/default/objects/Trigger_Action__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

application/base/main/default/classes/MetadataTriggerHandler.cls
/*
   Copyright 2020 Google LLC

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

public class MetadataTriggerHandler extends TriggerBase implements TriggerAction.BeforeInsert, TriggerAction.AfterInsert,  TriggerAction.BeforeUpdate, TriggerAction.AfterUpdate, TriggerAction.BeforeDelete, TriggerAction.AfterDelete, TriggerAction.AfterUndelete {
	@TestVisible
	private static Set<String> bypassedActions;
	
	static {
		bypassedActions = new Set<String>();
	}
	
	public void beforeInsert(List<SObject> newList) {
		try {
			for (TriggerAction.BeforeInsert action : beforeInsertActions) {
				action.beforeInsert(newList);
			}
		} catch (Exception e) {
			for (SObject obj : newList) {
				obj.addError(e.getMessage());
			}
		}
	}

	public void afterInsert(List<SObject> newList) {
		try {
			for (TriggerAction.AfterInsert action : afterInsertActions) {
				action.AfterInsert(newList);
			}
		} catch (Exception e) {
			for (SObject obj : newList) {
				obj.addError(e.getMessage());
			}
		}
	}

	public void beforeUpdate(List<SObject> newList, List<SObject> oldList) {
		try {
			for (TriggerAction.BeforeUpdate action : beforeUpdateActions) {
				action.BeforeUpdate(newList, oldList);
			}
		} catch (Exception e) {
			for (SObject obj : newList) {
				obj.addError(e.getMessage());
			}
		}
	}

	public void afterUpdate(List<SObject> newList, List<SObject> oldList) {
		try {
			for (TriggerAction.AfterUpdate action : AfterUpdateActions) {
				action.AfterUpdate(newList, oldList);
			}
		} catch (Exception e) {
			for (SObject obj : newList) {
				obj.addError(e.getMessage());
			}
		}
	}

	public void beforeDelete(List<SObject> oldList) {
		try {
			for (TriggerAction.BeforeDelete action : beforeDeleteActions) {
				action.BeforeDelete(oldList);
			}
		} catch (Exception e) {
			for (SObject obj : oldList) {
				obj.addError(e.getMessage());
			}
		}
	}

	public void afterDelete(List<SObject> oldList) {
		try {
			for (TriggerAction.AfterDelete action : afterDeleteActions) {
				action.AfterDelete(oldList);
			}
		} catch (Exception e) {
			for (SObject obj : oldList) {
				obj.addError(e.getMessage());
			}
		}
	}

	public void afterUndelete(List<SObject> newList) {
		try {
			for (TriggerAction.AfterUndelete action : afterUndeleteActions) {
				action.AfterUndelete(newList);
			}
		} catch (Exception e) {
			for (SObject obj : newList) {
				obj.addError(e.getMessage());
			}
		}
	}
	
	private List<TriggerAction.BeforeInsert> beforeInsertActions {
		get {
			List<TriggerAction.BeforeInsert> returnValue = new List<TriggerAction.BeforeInsert>();
			for (Trigger_Action__mdt triggerMetadata : triggerActionsForThisObject) {
				if (triggerMetadata.Before_Insert__c != null) {
					try {
						returnValue.add((TriggerAction.BeforeInsert)(Type.forName(triggerMetadata.Apex_Class_Name__c).newInstance()));
					} catch (System.TypeException e) {
						throw new CustomMetadataTriggerHandlerException(String.format(INVALID_TYPE_ERROR, new List<String> {triggerMetadata.Apex_Class_Name__c, String.valueOf(System.TriggerOperation.BEFORE_INSERT)}));
					}
				}
			}
			return returnValue;
		}
	}
	
	private List<TriggerAction.AfterInsert> afterInsertActions {
		get {
			List<TriggerAction.AfterInsert> returnValue = new List<TriggerAction.AfterInsert>();
			for (Trigger_Action__mdt triggerMetadata : triggerActionsForThisObject) {
				if (triggerMetadata.After_Insert__c != null) {
					try {
						returnValue.add((TriggerAction.AfterInsert)(Type.forName(triggerMetadata.Apex_Class_Name__c).newInstance()));
					} catch (System.TypeException e) {
						throw new CustomMetadataTriggerHandlerException(String.format(INVALID_TYPE_ERROR, new List<String> {triggerMetadata.Apex_Class_Name__c, String.valueOf(System.TriggerOperation.AFTER_INSERT)}));
					}
				}
			}
			return returnValue;
		}
	}
	
	private List<TriggerAction.BeforeUpdate> beforeUpdateActions {
		get {
			List<TriggerAction.BeforeUpdate> returnValue = new List<TriggerAction.BeforeUpdate>();
			for (Trigger_Action__mdt triggerMetadata : triggerActionsForThisObject) {
				if (triggerMetadata.Before_Update__c != null) {
					try {
						returnValue.add((TriggerAction.BeforeUpdate)(Type.forName(triggerMetadata.Apex_Class_Name__c)).newInstance());
					} catch (System.TypeException e) {
						throw new CustomMetadataTriggerHandlerException(String.format(INVALID_TYPE_ERROR, new List<String> {triggerMetadata.Apex_Class_Name__c, String.valueOf(System.TriggerOperation.BEFORE_UPDATE)}));
					}
				}
			}
			return returnValue;
		}
	}
	private List<TriggerAction.AfterUpdate> afterUpdateActions {
		get {
			List<TriggerAction.AfterUpdate> returnValue = new List<TriggerAction.AfterUpdate>();
			for (Trigger_Action__mdt triggerMetadata : triggerActionsForThisObject) {
				if (triggerMetadata.After_Update__c != null) {
					try {
						returnValue.add((TriggerAction.AfterUpdate)(Type.forName(triggerMetadata.Apex_Class_Name__c)).newInstance());
					} catch (System.TypeException e) {
						throw new CustomMetadataTriggerHandlerException(String.format(INVALID_TYPE_ERROR, new List<String> {triggerMetadata.Apex_Class_Name__c, String.valueOf(System.TriggerOperation.AFTER_UPDATE)}));
					}
				}
			}
			return returnValue;
		}
	}
	
	private List<TriggerAction.BeforeDelete> beforeDeleteActions {
		get {
			List<TriggerAction.BeforeDelete> returnValue = new List<TriggerAction.BeforeDelete>();
			for (Trigger_Action__mdt triggerMetadata : triggerActionsForThisObject) {
				if (triggerMetadata.Before_Delete__c != null) {
					try {
						returnValue.add((TriggerAction.BeforeDelete)(Type.forName(triggerMetadata.Apex_Class_Name__c)).newInstance());
					} catch (System.TypeException e) {
						throw new CustomMetadataTriggerHandlerException(String.format(INVALID_TYPE_ERROR, new List<String> {triggerMetadata.Apex_Class_Name__c, String.valueOf(System.TriggerOperation.BEFORE_DELETE)}));
					}
				}
			}
			return returnValue;
		}
	}
	
	private List<TriggerAction.AfterDelete> afterDeleteActions {
		get {
			List<TriggerAction.AfterDelete> returnValue = new List<TriggerAction.AfterDelete>();
			for (Trigger_Action__mdt triggerMetadata : triggerActionsForThisObject) {
				if (triggerMetadata.After_Delete__c != null) {
					try {
						returnValue.add((TriggerAction.AfterDelete)(Type.forName(triggerMetadata.Apex_Class_Name__c)).newInstance());
					} catch (System.TypeException e) {
						throw new CustomMetadataTriggerHandlerException(String.format(INVALID_TYPE_ERROR, new List<String> {triggerMetadata.Apex_Class_Name__c, String.valueOf(System.TriggerOperation.AFTER_DELETE)}));
					}
				}
			}
			return returnValue;
		}
	}
	
	private List<TriggerAction.AfterUndelete> afterUndeleteActions {
		get {
			List<TriggerAction.AfterUndelete> returnValue = new List<TriggerAction.AfterUndelete>();
			for (Trigger_Action__mdt triggerMetadata : triggerActionsForThisObject) {
				if (triggerMetadata.After_Undelete__c != null) {
					try {
						returnValue.add((TriggerAction.AfterUndelete)(Type.forName(triggerMetadata.Apex_Class_Name__c)).newInstance());
					} catch (System.TypeException e) {
						throw new CustomMetadataTriggerHandlerException(String.format(INVALID_TYPE_ERROR, new List<String> {triggerMetadata.Apex_Class_Name__c, String.valueOf(System.TriggerOperation.AFTER_UNDELETE)}));
					}
				}
			}
			return returnValue;
		}
	}
	
	
	@TestVisible
	private List<Trigger_Action__mdt> triggerActionsForThisObject {
		get {
			if (triggerActionsForThisObject == null) {
				triggerActionsForThisObject = new List<Trigger_Action__mdt>();
				List<sObject_Trigger_Setting__mdt> sobjectTriggerSettings = new List<sObject_Trigger_Setting__mdt>(
					[SELECT
						 (SELECT Id, Before_Insert__c, After_Insert__c, Before_Update__c, After_Update__c,
						 Before_Delete__c, After_Delete__c, After_Undelete__c, Apex_Class_Name__c, Order__c
						 FROM Before_Insert_Actions__r
						 WHERE Apex_Class_Name__c NOT IN: MetadataTriggerHandler.bypassedActions
						 ORDER BY Order__c ASC),
					 (SELECT Id, Before_Insert__c, After_Insert__c, Before_Update__c, After_Update__c,
					  Before_Delete__c, After_Delete__c, After_Undelete__c, Apex_Class_Name__c, Order__c
					  FROM After_Insert_Actions__r
					  WHERE Apex_Class_Name__c NOT IN: MetadataTriggerHandler.bypassedActions
					  ORDER BY Order__c ASC),
					 (SELECT Id, Before_Insert__c, After_Insert__c, Before_Update__c, After_Update__c,
					  Before_Delete__c, After_Delete__c, After_Undelete__c, Apex_Class_Name__c, Order__c
					  FROM Before_Update_Actions__r
					  WHERE Apex_Class_Name__c NOT IN: MetadataTriggerHandler.bypassedActions
					  ORDER BY Order__c ASC),
					 (SELECT Id, Before_Insert__c, After_Insert__c, Before_Update__c, After_Update__c,
					  Before_Delete__c, After_Delete__c, After_Undelete__c, Apex_Class_Name__c, Order__c
					  FROM After_Update_Actions__r
					  WHERE Apex_Class_Name__c NOT IN: MetadataTriggerHandler.bypassedActions
					  ORDER BY Order__c ASC),
					 (SELECT Id, Before_Insert__c, After_Insert__c, Before_Update__c, After_Update__c,
					  Before_Delete__c, After_Delete__c, After_Undelete__c, Apex_Class_Name__c, Order__c
					  FROM Before_Delete_Actions__r
					  WHERE Apex_Class_Name__c NOT IN: MetadataTriggerHandler.bypassedActions
					  ORDER BY Order__c ASC),
					 (SELECT Id, Before_Insert__c, After_Insert__c, Before_Update__c, After_Update__c,
					  Before_Delete__c, After_Delete__c, After_Undelete__c, Apex_Class_Name__c, Order__c
					  FROM After_Delete_Actions__r
					  WHERE Apex_Class_Name__c NOT IN: MetadataTriggerHandler.bypassedActions
					  ORDER BY Order__c ASC),
					 (SELECT Id, Before_Insert__c, After_Insert__c, Before_Update__c, After_Update__c,
					  Before_Delete__c, After_Delete__c, After_Undelete__c, Apex_Class_Name__c, Order__c
					  FROM After_Undelete_Actions__r
					  WHERE Apex_Class_Name__c NOT IN: MetadataTriggerHandler.bypassedActions
					  ORDER BY Order__c ASC)
					 FROM sObject_Trigger_Setting__mdt
					 WHERE SObject__r.DeveloperName =: this.sObjectName
									  AND Bypass_Execution__c = false
												    LIMIT 1
					]
					);
				if (!sobjectTriggerSettings.isEmpty()) {
					triggerActionsForThisObject.addAll(sobjectTriggerSettings[0].Before_Insert_Actions__r);
					triggerActionsForThisObject.addAll(sobjectTriggerSettings[0].After_Insert_Actions__r);
					triggerActionsForThisObject.addAll(sobjectTriggerSettings[0].Before_Update_Actions__r);
					triggerActionsForThisObject.addAll(sobjectTriggerSettings[0].After_Update_Actions__r);
					triggerActionsForThisObject.addAll(sobjectTriggerSettings[0].Before_Delete_Actions__r);
					triggerActionsForThisObject.addAll(sobjectTriggerSettings[0].After_Delete_Actions__r);
					triggerActionsForThisObject.addAll(sobjectTriggerSettings[0].After_Undelete_Actions__r);
				}
			}
			return triggerActionsForThisObject;
		}
		set;
	}
	
	public static void bypass(String actionName) {
		MetadataTriggerHandler.bypassedActions.add(actionName);
	}
	
	public static void clearBypass(String actionName) {
		MetadataTriggerHandler.bypassedActions.remove(actionName);
	}
	
	public static Boolean isBypassed(String actionName) {
		return MetadataTriggerHandler.bypassedActions.contains(actionName);
	}
	
	public static void clearAllBypasses() {
		MetadataTriggerHandler.bypassedActions.clear();
	}
	
	@TestVisible
	private static final String INVALID_TYPE_ERROR = 'Trigger Action Custom Metadata is configured incorrectly for class {0}. Either the class does not exist, or it exists and does not implement the Trigger Action interface specified for the {1} context.';
	
	class CustomMetadataTriggerHandlerException extends Exception {}
	
	
}