trigger-actions-framework/main/default/objects/sObject_Trigger_Setting__mdt/sObject_Trigger_Setting__mdt.object-meta.xml
<CustomObject>
    <label>sObject Trigger Setting</label>
    <pluralLabel>sObject Trigger Settings</pluralLabel>
</CustomObject>

trigger-actions-framework/main/default/objects/sObject_Trigger_Setting__mdt/fields/Formula_Evaluation_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Formula_Evaluation_Class_Name__c</fullName>
    <description>Enter the API name of a global class which contains two global properties: `record`
        and `recordPrior`. Both of these variables need to match the SObject type for this SObject
        Trigger Setting record.</description>
    <inlineHelpText>Enter the API name of a global class which contains two global properties:
        `record` and `recordPrior`. Both of these variables need to match the SObject type for this
        SObject Trigger Setting record.</inlineHelpText>
    <label>Formula Evaluation Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/Trigger_Action__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Action</label>
    <pluralLabel>Trigger Actions</pluralLabel>
</CustomObject>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Before_Update__c.field-meta.xml
<CustomField>
    <fullName>Before_Update__c</fullName>
    <description>Enter the name of the sObject you want to have this action execute on during the before update context</description>
    <inlineHelpText>Enter the name of the sObject you want to have this action execute on during the before update context</inlineHelpText>
    <label>Before Update</label>
    <referenceTo>sObject_Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>Before Update</relationshipLabel>
    <relationshipName>Before_Update_Actions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

trigger-actions-framework/main/default/objects/Trigger_Action__mdt/fields/Entry_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Entry_Criteria__c</fullName>
    <description>Apex formula which if evaluated to true for a given record during trigger processing, then this trigger action will be processed for that record.</description>
    <inlineHelpText>Apex formula which if evaluated to true for a given record during trigger processing, then this trigger action will be processed for that record.</inlineHelpText>
    <label>Entry Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

trigger-actions-framework/main/default/classes/FormulaFilterTest.cls
/*
   Copyright 2024 Google LLC

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

	https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
@SuppressWarnings(
	'PMD.ApexUnitTestClassShouldHaveRunAs, PMD.AvoidGlobalModifier'
)
@IsTest
global class FormulaFilterTest {
	private static final String ACCOUNT_SOBJECT_NAME = 'Account';
	private static List<Account> newList = new List<Account>{
		new Account(Name = 'Test Account 1'),
		new Account(Name = 'Test Account 2')
	};
	private static List<Account> oldList = new List<Account>{
		new Account(Name = 'Test Account 1'),
		new Account(Name = 'Test Account 2')
	};
	private static sObject_Trigger_Setting__mdt sobjectSetting = new sObject_Trigger_Setting__mdt(
		Formula_Evaluation_Class_Name__c = 'FormulaFilterTest.AccountTriggerRecord'
	);
	private static Trigger_Action__mdt configuration = new Trigger_Action__mdt(
		Before_Update__r = sobjectSetting
	);

	@IsTest
	private static void noFormulaShouldProcessAllRecords() {
		FormulaFilter filter = new FormulaFilter(
			configuration,
			TriggerOperation.BEFORE_UPDATE,
			ACCOUNT_SOBJECT_NAME
		);

		FormulaFilter.Result result = filter.filterByEntryCriteria(
			newList,
			oldList
		);

		System.assertEquals(
			2,
			result.newList.size(),
			'The size of newList should be 2'
		);
		System.assertEquals(
			2,
			result.oldList.size(),
			'The size of oldList should be 2'
		);
	}

	@IsTest
	private static void emptyStringFormulaShouldProcessAllRecords() {
		configuration.Entry_Criteria__c = '';

		FormulaFilter filter = new FormulaFilter(
			configuration,
			TriggerOperation.BEFORE_UPDATE,
			ACCOUNT_SOBJECT_NAME
		);

		FormulaFilter.Result result = filter.filterByEntryCriteria(
			newList,
			oldList
		);

		System.assertEquals(
			2,
			result.newList.size(),
			'The size of newList should be 2'
		);
		System.assertEquals(
			2,
			result.oldList.size(),
			'The size of newList should be 2'
		);
	}

	@IsTest
	private static void validFormulaShouldFilterContentsOfNewList() {
		configuration.Entry_Criteria__c = 'record.Name = "Test Account 1"';

		FormulaFilter filter = new FormulaFilter(
			configuration,
			TriggerOperation.BEFORE_UPDATE,
			ACCOUNT_SOBJECT_NAME
		);

		FormulaFilter.Result result = filter.filterByEntryCriteria(
			newList,
			oldList
		);

		System.assertEquals(
			1,
			result.newList.size(),
			'There should be 1 record in newList'
		);
		System.Assert.areEqual(
			'Test Account 1',
			((Account) result.newList[0]).Name,
			'The first record newList should have a name of Test Account 1'
		);
		System.assertEquals(
			1,
			result.oldList.size(),
			'There should be 1 record in newList'
		);
		System.Assert.areEqual(
			'Test Account 1',
			((Account) result.oldList[0]).Name,
			'The first record newList should have a name of Test Account 1'
		);
	}

	@IsTest
	private static void validFormulaWithNoMatchingRecordsShouldProcessNoRecords() {
		configuration.Entry_Criteria__c = 'record.Name = "FooBar"';

		FormulaFilter filter = new FormulaFilter(
			configuration,
			TriggerOperation.BEFORE_UPDATE,
            ACCOUNT_SOBJECT_NAME
		);

		FormulaFilter.Result result = filter.filterByEntryCriteria(
			newList,
			oldList
		);

		System.Assert.isNotNull(result, 'result should not be null');
		System.Assert.isTrue(result.newList.isEmpty(), 'newList should be empty');
		System.Assert.isTrue(result.oldList.isEmpty(), 'oldList should be empty');
	}

	@SuppressWarnings('PMD.ApexDoc')
	global class AccountTriggerRecord extends TriggerRecord {
		global Account record {
			get {
				return (Account) this.newSObject;
			}
		}
		global Account recordPrior {
			get {
				return (Account) this.oldSObject;
			}
		}
	}
}